### ISSUE TITLE
Switched my Reverse Proxy to Caddy and now get Error 308 on query

### ISSUE THREAD

**Issue by dreimer1986** [kingfisher63/avm_juischeck#21]
Accessing the Fritz!Box and a buch of repeaters works fine with the new reverse proxy, just way more stable and faster than NGINX did. Any browser happily complies and shows the site. But JuisCheck runs into an error.

![image](https://github.com/kingfisher63/avm_juischeck/assets/29841368/e2d5c4f0-b617-4f3b-b94f-b0fec8199bae)

Any idea?

Caddy does nothing special here. HTTPS (external)-> HTTP (internal) transition is the only thing worth mentioning. But this was done on NGINX side, too.

**Comment by kingfisher63** [comment]
JuisCheck retrieves device information using a HTTP URL as HTTPS will not work (the FRITZ!Box self signed certificate is considered invalid as it does not have a trusted root). FRITZ! devices do not generate redirects, so my working assumption is that your reverse proxy causes a redirect from HTTP to HTTPS. Apparently _System.Xml.XmlReader_ in .NET Framework does not support redirects (unfortunately Microsoft documentation is silent on this).

Please verify that your reverse proxy is indeed returning redirects for HTTP requests. If so, it should be possible to configure it to accept HTTP requests to your FRITZ! devices (specifically http://.../juis_boxinfo.xml) instead of generating a redirect. The HTTPS->HTTP mapping by the proxy is immaterial.

**Comment by dreimer1986** [comment]
Tested a slightly modified config variant without redirect. Works fine. So this can be closed ^^
