### ISSUE TITLE
Repeater 1200x/2400 update auf 7.57 funktioniert nicht

### ISSUE THREAD

**Issue by jopi56** [kingfisher63/avm_juischeck#22]
Ich habe mehere 1200ax- und 2400er-Repeater.
Diese haben diese Woche ein Update auf Version 7.57 bekommen.
Ich hatte auf allen Repeatern die Version 7.56 installiert gehabt.
Ich kontrolliere nur den Release-Kanal.
Bei keinem Repeater wurde ein Update gemeldet.

**Comment by kingfisher63** [comment]
JuisCheck is merely a GUI front end for querying the AVM Update Information Service (JUIS). Therefore JuisCheck will only show an update if JUIS indicates that there is an update for the given parameters.

AVM has not (yet) configured 7.57 as an update for 7.56 in JUIS. As a result JuisCheck will not find 7.57 when using 7.56 as the current version, nor will a FRITZ!Repeater 1200AX or 2400 running 7.56. JuisCheck will find 7.57 though if you use the previous release (7.30 for the 1200AX, 7.50 for the 2400) as the current version, so the current behavior may be intentional. You may want to contact AVM Support if you think this is an error nevertheless.
